Add support for skip-services

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -29,11 +29,11 @@ inputs:
     required: false
     default: 'none'
   wordpress-version:
-    description: 'Install WordPress related services for WP version'
+    description: 'Specify the WordPress version to use (false to skip)'
     required: false
     default: 'latest'
   wordpress-multisite:
-    description: 'Enable WordPress multisite'
+    description: 'Enable WordPress multisite (only works with wordpress-version)'
     required: false
     default: 'false'
   wordpress-host:
@@ -92,6 +92,14 @@ inputs:
     description: 'GitHub token for accessing private repositories via composer'
     required: false
     default: ''
+  skip-services:
+    description: 'Skip starting Docker-based services (mysql, redis, memcached)'
+    required: false
+    default: 'false'
+  services-skip:
+    description: 'Skip starting Docker-based services (mysql, redis, memcached)'
+    required: false
+    default: 'false'
 
 runs:
   using: 'composite'
@@ -102,6 +110,19 @@ runs:
         echo "SKIP_INSTALL=$([ "${{ inputs.install-skip }}" = "true" ] || [ "${{ inputs.skip-install }}" = "true" ] && echo "true" || echo "false")" >> $GITHUB_ENV
         echo "SKIP_AUDIT=$([ "${{ inputs.audit-skip }}" = "true" ] || [ "${{ inputs.skip-audit }}" = "true" ] && echo "true" || echo "false")" >> $GITHUB_ENV
         echo "SKIP_TEST=$([ "${{ inputs.test-skip }}" = "true" ] || [ "${{ inputs.skip-test }}" = "true" ] && echo "true" || echo "false")" >> $GITHUB_ENV
+        echo "SKIP_SERVICES=$([ "${{ inputs.services-skip }}" = "true" ] || [ "${{ inputs.skip-services }}" = "true" ] && echo "true" || echo "false")" >> $GITHUB_ENV
+      shell: bash
+
+    - name: Environmental variable consistency check
+      run: |
+        # Test for incompatible / unsupported options:
+
+        # If SKIP_SERVICES is true and wordpress-version is not false, fail
+        if [ "${{ env.SKIP_SERVICES }}" = "true" ] && [ "${{ inputs.wordpress-version }}" != "false" ]; then
+          unsupported_configuration=true
+          echo "wordpress-version != false requires SKIP_SERVICES to be false" >&2
+          exit 1
+        fi
       shell: bash
 
     - name: Generate extension hash per PHP version and extensions
@@ -154,8 +175,8 @@ runs:
         restore-keys: |
           ${{ runner.os }}-composer-${{ inputs.php-version }}-${{ hashFiles(inputs.cache-dependency-path) }}
 
-    - name: Start WordPress services in the background
-      if: ${{ inputs.wordpress-version != 'false' }}
+    - name: Start services in the background
+      if: ${{ env.SKIP_SERVICES != 'true' }}
       run: |
         docker-compose -f ${{ github.action_path }}/docker-compose.yml up -d
       shell: bash
@@ -172,8 +193,8 @@ runs:
       shell: bash
       working-directory: ${{ inputs.working-directory }}
 
-    - name: Wait for WordPress services if needed
-      if: ${{ inputs.wordpress-version != 'false' && env.SKIP_TEST != 'true' }}
+    - name: Wait for services if needed
+      if: ${{ env.SKIP_SERVICES != 'true' }}
       run: |
         echo "Waiting for MySQL, Redis, and Memcached to become healthy..."
         timeout=30  # Timeout after 30 seconds
